import React from 'react';
import { FactAnalysisResult } from '../types';
import MarkdownRenderer from './MarkdownRenderer';
import { Calendar, AlertTriangle, CheckCircle, XCircle, Download, Scale } from 'lucide-react';

interface FactReportProps {
    result: FactAnalysisResult;
}

const FactReport: React.FC<FactReportProps> = ({ result }) => {

    const getEventColor = (type: string) => {
        switch (type) {
            case 'contract': return 'bg-blue-500';
            case 'payment': return 'bg-green-500';
            case 'breach': return 'bg-red-600';
            case 'dispute': return 'bg-amber-500';
            default: return 'bg-slate-400';
        }
    };

    const handleExportWord = async () => {
        try {
            // 简单的 Markdown 转 HTML (基础实现)
            const contentHtml = result.markdownReport
                .replace(/^# (.*$)/gm, '<h1 style="font-size: 18pt; font-weight: bold; text-align: center; margin-bottom: 20px;">$1</h1>')
                .replace(/^## (.*$)/gm, '<h2 style="font-size: 16pt; font-weight: bold; margin-top: 15px; background-color: #f0f0f0; padding: 5px;">$1</h2>')
                .replace(/^### (.*$)/gm, '<h3 style="font-size: 14pt; font-weight: bold; margin-top: 10px;">$1</h3>')
                .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                .replace(/\n/g, '<br/>');

            const fullHtml = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
          <meta charset='utf-8'>
          <title>法律事实梳理意见书</title>
          <style>
            body { font-family: 'SimSun', 'Songti SC', serif; font-size: 12pt; line-height: 1.5; }
          </style>
        </head>
        <body>
          <h1 style="text-align: center;">法律事实梳理意见书</h1>
          ${contentHtml}
          <br/>
          <hr/>
          <p style="text-align: right; color: #888; font-size: 10pt;">Generated by AI 建工法律咨询系统</p>
        </body>
        </html>
      `;

            const blob = new Blob([fullHtml], { type: 'application/msword' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `法律事实梳理意见书_${new Date().toISOString().split('T')[0]}.doc`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        } catch (e) {
            console.error("Export failed", e);
            alert("导出失败，请重试");
        }
    };

    const hasBreach = result.timeline.some(t => t.type === 'breach');

    return (
        <div className="bg-white rounded-xl shadow-lg overflow-hidden border border-slate-200 animate-fade-in">
            {/* Header - 使用琥珀/深色主题 */}
            <div className="bg-slate-900 text-white p-6">
                <div className="flex justify-between items-start">
                    <div className="flex items-center space-x-3">
                        <div className="p-2 bg-amber-600 rounded-lg">
                            <Scale className="w-5 h-5 text-white" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold font-serif">法律事实梳理意见书</h2>
                            <p className="text-slate-400 text-sm mt-1">AI 建工法律咨询系统 · 事实梳理引擎</p>
                        </div>
                    </div>
                    <div className="flex gap-2 items-center">
                        <span className="px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs border border-amber-500/30">
                            建工专版
                        </span>
                        <button
                            onClick={handleExportWord}
                            className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-slate-700 hover:bg-slate-600 text-white text-xs border border-slate-600 transition-colors"
                        >
                            <Download className="w-3 h-3" />
                            导出 Word
                        </button>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3">
                {/* 主内容区 - Markdown 报告 */}
                <div className="lg:col-span-2 p-8 border-r border-slate-100">
                    <div className="prose prose-slate max-w-none">
                        <MarkdownRenderer content={result.markdownReport} />
                    </div>
                </div>

                {/* 侧边栏 - 状态与时间轴 */}
                <div className="bg-slate-50 p-6 space-y-6">

                    {/* 履行状态卡片 */}
                    <div className="bg-white p-4 rounded-lg shadow-sm border border-slate-200">
                        <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-3">履行状态分析</h3>
                        <div className="flex items-center space-x-3">
                            {hasBreach ? (
                                <>
                                    <div className="p-2 bg-red-100 text-red-700 rounded-full">
                                        <XCircle className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="text-lg font-bold text-slate-800">存在根本违约</p>
                                        <p className="text-xs text-slate-500">依据"触发点锁定法则"判定</p>
                                    </div>
                                </>
                            ) : (
                                <>
                                    <div className="p-2 bg-green-100 text-green-700 rounded-full">
                                        <CheckCircle className="w-5 h-5" />
                                    </div>
                                    <div>
                                        <p className="text-lg font-bold text-slate-800">阶段性履约</p>
                                        <p className="text-xs text-slate-500">依据资金闭环逻辑判定</p>
                                    </div>
                                </>
                            )}
                        </div>
                    </div>

                    {/* 关键事件轴 */}
                    {result.timeline.length > 0 && (
                        <div>
                            <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4 flex items-center">
                                <Calendar className="w-4 h-4 mr-2" />
                                关键事件轴
                            </h3>
                            <div className="relative border-l-2 border-slate-200 ml-3 space-y-6">
                                {result.timeline.map((item, idx) => (
                                    <div key={idx} className="mb-4 ml-6 relative">
                                        <span className={`
                      absolute -left-[31px] top-1 w-4 h-4 rounded-full border-2 border-white shadow-sm
                      ${getEventColor(item.type)}
                    `}></span>
                                        <time className="block mb-1 text-sm font-normal leading-none text-slate-400">
                                            {item.date}
                                        </time>
                                        <h4 className="text-sm font-semibold text-slate-900">
                                            {item.event}
                                        </h4>
                                        {item.citation && (
                                            <span className="text-xs text-amber-600 bg-amber-50 px-2 py-0.5 rounded border border-amber-100 mt-1 inline-block">
                                                {item.citation}
                                            </span>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* AI 推理提示 */}
                    <div className="bg-amber-50 border border-amber-200 p-4 rounded-lg">
                        <div className="flex items-start">
                            <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 mr-2 flex-shrink-0" />
                            <div>
                                <h4 className="text-sm font-bold text-amber-800">AI 推理引擎提示</h4>
                                <p className="text-xs text-amber-700 mt-1 leading-relaxed">
                                    已启用 <strong>Hierarchy Logic</strong> (效力金字塔)。
                                    若检测到《补充协议》包含"以本协议为准"条款，系统将自动覆盖旧合同的工期与赔偿计算标准。
                                </p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
};

export default FactReport;
